#!/bin/sh
set -eu

ROOT="${CLAUDE_PROJECT_DIR:-$PWD}"
query="$(cat | jq -r '.query // ""')"

qnorm="$(printf "%s" "$query" | tr '[:upper:]' '[:lower:]' | tr -cd '[:alnum:]')"

bfs "$ROOT" \
  -exclude -name .git -exclude -name node_modules -exclude -name .venv \
  -type f \
  2>/dev/null |
  sed "s|^$ROOT/||" |
  awk -v q="$qnorm" '
    function norm(s) {
      s = tolower(s)
      gsub(/[^[:alnum:]]+/, "", s)
      return s
    }

    function is_subseq(s, q,    i, j, cs, cq) {
      if (q == "") return 1
      i = 1
      for (j = 1; j <= length(s) && i <= length(q); j++) {
        cs = substr(s, j, 1)
        cq = substr(q, i, 1)
        if (cs == cq) i++
      }
      return (i > length(q))
    }

    BEGIN { n = 0 }
    {
      p = $0
      s = norm(p)

      if (is_subseq(s, q)) {
        print p
        n++
        if (n >= 15) exit
      }
    }
  '

